spring.application.name=backend
spring.datasource.url=${CANAPA_DB_URL:jdbc:postgresql://localhost:5432/canapa}
spring.datasource.username=${CANAPA_DB_USERNAME:${user.name}}
spring.datasource.password=${CANAPA_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
