package org.spring.canapa.backend.api.error;

public enum ApiErrorCode {
    INVALID_REQUEST,
    USER_NOT_FOUND,
    DUPLICATE_USER_DATA,
    ROOM_NOT_FOUND,
    ROOM_PARTICIPANT_ALREADY_EXISTS,
    ROOM_JOIN_NOT_ALLOWED,
    INVALID_ROOM_STATUS_TRANSITION,
    ROOM_ACTION_NOT_ALLOWED
}
